// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCszHLaXX7_1oZHHJko_LtIhjofY3TUsO8',
    appId: '1:728466681157:web:e238a9dec662d38227e22c',
    messagingSenderId: '728466681157',
    projectId: 'uhakae-app',
    authDomain: 'uhakae-app.firebaseapp.com',
    storageBucket: 'uhakae-app.firebasestorage.app',
    measurementId: 'G-YDN142XQ75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYIucFidwg2zs5_2_6-l_noZSRWQy69Y',
    appId: '1:728466681157:android:db520b0f5ac614ed27e22c',
    messagingSenderId: '728466681157',
    projectId: 'uhakae-app',
    storageBucket: 'uhakae-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kztWa02WQUsZlXO33vUdt29An0clgwU',
    appId: '1:728466681157:ios:2672e9909129d6a827e22c',
    messagingSenderId: '728466681157',
    projectId: 'uhakae-app',
    storageBucket: 'uhakae-app.firebasestorage.app',
    iosBundleId: 'com.example.studyAbroadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kztWa02WQUsZlXO33vUdt29An0clgwU',
    appId: '1:728466681157:ios:2672e9909129d6a827e22c',
    messagingSenderId: '728466681157',
    projectId: 'uhakae-app',
    storageBucket: 'uhakae-app.firebasestorage.app',
    iosBundleId: 'com.example.studyAbroadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCszHLaXX7_1oZHHJko_LtIhjofY3TUsO8',
    appId: '1:728466681157:web:310eb225c2448d2e27e22c',
    messagingSenderId: '728466681157',
    projectId: 'uhakae-app',
    authDomain: 'uhakae-app.firebaseapp.com',
    storageBucket: 'uhakae-app.firebasestorage.app',
    measurementId: 'G-P4D35RDHZK',
  );
}
